### ISSUE TITLE
[1.12.2] Looking at bedrock ore causes font rendering problem when using The Betweenlands

### ISSUE THREAD

**Issue by SeriousCreeper** [MightyPirates/BedrockOres#52] opened 2017-12-28 23:37 UTC
Heya,

not sure which mod would be the causer for this problem, but since this only triggers when looking at the bedrock ores, i figured i'll report it here. 

I'm using the latest version of bedrock ore, forge, and the betweenlands. 
The font is fine everywhere, until i look at a bedrock ore. Then suddenly the font changes/breaks for everything in the game. Even when i quit the world and go to the main menu, all the text on every button is broken as well. 

Example:
https://i.imgur.com/VtEHSBn.png
https://i.imgur.com/EDyIFFi.png

Let me know if i can provide anything else. 

Also pinging @TheCyberBrick just in case!

Thanks,
SC

**Comment by TheCyberBrick** [comment] 2017-12-28 23:53
Is this only happening with the Betweenlands installed? I just tried it out myself with Betweenlands and Bedrock Ores only and I couldn't reproduce it

**Comment by SeriousCreeper** [comment] 2017-12-28 23:57
I had The One Probe as well but just took it out and i still get the same result. It only changes the font when i look at a bedrock ore (and it pops up the "Expected Yield" text. 
I haven't seen it happen with any other mod yet. In one of my bigger mod setups, as soon as i disable Betweenlands, it seems fine.

**Comment by TheCyberBrick** [comment] 2018-01-01 02:05
Are there any OpenGL (GL) errors in the log?

**Comment by SeriousCreeper** [comment] 2018-01-02 05:00
Hm not seeing any OpenGL errors. 
Also snippet from the log: https://pastebin.com/d6vvTkE7

And screenshots of my debug screen, for info about GPU, java, etc. Not sure if any of this helps: https://i.imgur.com/R20vb9r.png

**Comment by Flashwar** [comment] 2018-01-03 19:56
same here 
![2018-01-03_20 55 30](https://user-images.githubusercontent.com/13320784/34537380-7ed118b8-f0c8-11e7-9fbf-de51ca935aa7.png)

**Comment by TheCyberBrick** [comment] 2018-01-05 11:43
Will be fixed in the next Betweenalnds version

**Comment by fnuecke** [comment] 2018-01-30 18:32
I'm not aware of changing the GL state anywhere not involving the GlStateManager (and I'm not using push/popAttrib either, which when used alongside the GlStateManager can break stuff). So I'm not sure how I could try to work against this.

If any additional information becomes available and there is something I can fix in BedrockOres, please let me know and reopen this issue.

**Closed as completed by fnuecke** 2018-01-30 18:32 UTC
