### ISSUE TITLE
Explosions destroy Ores

### ISSUE THREAD

**Issue by darkshadow543** [MightyPirates/BedrockOres#21] opened 2017-08-31 03:26 UTC
If the ore were embedded in bedrock, then it would make sense that it would not be destroyed by an explosion.  Yet this is the case with NFLN from tinkers construct and IE's powder barrel

**Comment by fnuecke** [comment] 2017-08-31 07:24
Hmm, because the explosion probably also uses the contained ore to check for hardness... will have to see how I can special-case that.

**Comment by fnuecke** [comment] 2017-08-31 20:49
I cannot reproduce this, the ores are [properly indestructible](https://www.youtube.com/watch?v=6kRWMLugr9k) for me.
What version(s) did you test this with?

**Comment by darkshadow543** [comment] 2017-09-01 12:15
Sorry I did not report this earlier, but I was using modded explosives, the EFLN from tinkers, and the gunpower barrel from Immersive Engineering.  I was playing on 1.12.1 version of the mod.
https://youtu.be/fNQFOYFpYPE Ores are destructible.
Modpack: https://minecraft.curseforge.com/projects/naural-capitalism-revitalized
I'm currently developing this pack.

**Comment by fnuecke** [comment] 2017-09-01 13:49
Ah, something's different in 1.12 then, because I tested with those, too. Will have a look over the weekend!

**Comment by fnuecke** [comment] 2017-09-01 17:43
Yep, came in during the port to 1.12, the blocks simply had an incorrect hardness/resistance value. Fixed in MC1.12-1.0.4.22. Thanks for reporting!

57cd960cd0b5107737768914ca9d5a9fa9eabb69

**Closed as completed by fnuecke** 2017-09-01 17:43 UTC
