### ISSUE TITLE
Miner doesn't eject last ore

### ISSUE THREAD

**Issue by esotericist** [MightyPirates/BedrockOres#42] opened 2017-10-15 04:25 UTC
It looks like once the miner hits the 'exhausted' state, it doesn't eject the very last ore it's holding even though there's room in the inventory and it still has power.
This is on Bedrock Ores-MC1.12-1.2.3.34.jar, forge 2501.

I also suspect it doesn't successfully eject an ore if it had exactly enough energy to mine the ore, but not begin another operation; I gave a miner 100k energy, and it removed 25 ore from the node (started at 100, showed 75 remaining), but only put 24 in the chest.

**Comment by fnuecke** [comment] 2017-10-15 14:32
Can't reproduce that I'm afraid, works fine either way (fully exhausted or not, uses up energy exactly).

If you break the miner, does the last ore drop? I.e. is it actually still "in" the miner, or did it just disappear?
How reliably can you reproduce this? What mod do you use to power the miner?

**Comment by esotericist** [comment] 2017-10-16 00:27
I was using immersive engineering to power it.

I was in creative at the time testing stuff, so I didn't try breaking it, I did verify that there was an item in it while it was in the 'exhausted' state both through The One Probe and via nbtedit.

I can't rule out that I misunderstood what was happening during the power loss incident, but I'm certain that I had it holding on to one last item when it a) had power, b) had room in the chest above, and c) was claiming to be exhausted.

That said: I *was* using a block for testing that happened to be made using the `/bedrockores wrap` command, rather than a natural spawn. Could that have been the problem?

**Comment by fnuecke** [comment] 2018-01-30 21:18
Re-tested this again, ImmersiveEngineering-0.12-76, with a regular world-gen ore and a `/bedrockores wrap`ped one, no chance. If you can still reproduce this, mind zipping a minimal pack+world with the repro for me? Until that, closing for now.

**Closed as completed by fnuecke** 2018-01-30 21:18 UTC

**Comment by esotericist** [comment] 2018-02-03 10:22
Apologies, been taking a hiatus from minecraft a while due to competing time pressures, so this is totally fair. Will totally report back if i can reproduce it again next time I have time to play.
